baseURL                = "http://e-onion.netlify.app"
defaultContentLanguage = "ja"
hasCJKLanguage         = true
languageCode           = "ja-jp"
theme                  = "ronu-hugo-theme"
title                  = "うぃーくりー・あんだーわーるど・にゅーす"

[params]
AuthorName             = "Ned Rihine"
GitHubUser             = "noqisofon"


[permalinks]
posts                  = "/:year/:month/:day/:filename/"

[[menu.main]]
name                   = "Archive"
url                    = "/posts"
weight                 = 1

[markup]

[markup.highlight]
codeFences             = true
guessSyntax            = true
hl_Lines               = ""
lineNos                = true
lineNoStart            = 1
lineNumberInTable      = false
noClasses              = true
style                  = "github"
tabWidth               = 4