[build]
command             = "hugo --gc --minify -b $URL"
publish             = "public"

[build.environment]
HUGO_VERSION        = "0.83.1"
HUGO_ENV            = "production"
HUGO_ENABLEGITINFO  = "true"
